/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/intensity/{zone}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Intensity
         * @description Measured and forecast carbon intensity (gCO2eq/kWh) for a zone.
         */
        get: operations["get_intensity_v1_intensity__zone__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule
         * @description Find the lowest-carbon start time and zone that still meets the deadline.
         */
        post: operations["schedule_v1_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zones
         * @description Countries with carbon intensity data, sorted by name.
         */
        get: operations["zones_v1_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntensityResponse */
        IntensityResponse: {
            /**
             * Attribution
             * @default Carbon intensity data: Energy-Charts.info, Fraunhofer ISE
             */
            attribution: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Points */
            points: components["schemas"]["PointOut"][];
            /** Resolution Minutes */
            resolution_minutes: number;
            /** Zone */
            zone: string;
        };
        /** PointOut */
        PointOut: {
            /** Gco2 Per Kwh */
            gco2_per_kwh: number;
            /** Is Forecast */
            is_forecast: boolean;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** ScheduleRequest */
        ScheduleRequest: {
            /**
             * Deadline
             * @description Latest time the job must finish. Defaults to the end of the forecast.
             */
            deadline?: string | null;
            /**
             * Duration Minutes
             * @example 120
             */
            duration_minutes: number;
            /**
             * Power Kw
             * @description Average power draw of the job. If set, emissions are returned in grams.
             * @example 0.4
             */
            power_kw?: number | null;
            /**
             * Zones
             * @description Zones the job may run in, in order of preference. The first one is used as the run-now baseline.
             * @example [
             *       "de",
             *       "fr",
             *       "nl"
             *     ]
             */
            zones: string[];
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /**
             * Attribution
             * @default Carbon intensity data: Energy-Charts.info, Fraunhofer ISE
             */
            attribution: string;
            /** Delay Minutes */
            delay_minutes: number;
            /** Emissions Saved G */
            emissions_saved_g: number | null;
            recommended: components["schemas"]["WindowOut"];
            /** @description Starting immediately in the first zone. Null if the data does not cover it. */
            run_now: components["schemas"]["WindowOut"] | null;
            /** Savings Pct */
            savings_pct: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WindowOut */
        WindowOut: {
            /** Avg Gco2 Per Kwh */
            avg_gco2_per_kwh: number;
            /** Emissions G */
            emissions_g?: number | null;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Uses Forecast */
            uses_forecast: boolean;
            /** Zone */
            zone: string;
        };
        /** ZoneOut */
        ZoneOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_intensity_v1_intensity__zone__get: {
        parameters: {
            query?: {
                include_past?: boolean;
            };
            header?: never;
            path: {
                /** @description ISO 3166-1 alpha-2 country code, e.g. de */
                zone: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntensityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_v1_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zones_v1_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"][];
                };
            };
        };
    };
}
